version: '3'
service:
    db:
        image: mongo:3.4
    backend:
        image: node:8.1
        volumes:
            - ./back:/back
        ports:
            - 3000:3000
        command: bash -c "cd /back && npm i && node app"
    frontend:
        image: nginx:1.13
        volumes:
            - ./fort:/usr/share/nginx/html
        ports:
            - 80:80