version: "3"
services:
    db:
        image: mongo:3.4
    back:
        image: node:8.1
        volumes:
            - ./back:/back
        ports:
            - 3000:3000
        command: bash -c "cd /back && npm i && node app"
    front:
        image: nginx:1.13
        volumes:
            - ./front:/usr/share/nginx/html
        ports:
            - 8080:80